### PR TITLE
Dev to main

### PR DESCRIPTION
**Pull request by th0mk**
- You can now search in the `.fmalbum` command. Simply enter the search values (artist and album name recommended) behind the command.
- Album cover is now shown in `.fmalbum` / `.fmab`
- You can now also search for albums in `.fmcover` / `.fmco`
- Added `.fmtrack` / `.fmtr` for track info. Supports searching for tracks.
- Fixed a bug where `.fmremoveallfriends` would delete you from other peoples friendlists
- Preparations for artist storing
- Preparations for better error logging
- `.fmchart` now uses less api calls and is faster
- Updated some static commands with our new OpenCollective link for supporting us (<https://opencollective.com/fmbot>)
- Removed top.gg upvote begging
- Added `plays` command for artists/albums/tracks.
Examples: 
- `.fmtrackplays` - `.fmtp` - `.fmtp kanye west stronger`
- `.fmalbumplays` - `.fmabp` - `.fmabp tame impala slow rush`
- `.fmartistplays` - `.fmap` - `.fmap Mall Grab`

### CODE REVIEW

**Comment by intcreator** [comment]
should these commands be added to the docs?

**Comment by th0mk** [comment]
Just checked, they're all already in the docs

**Comment by intcreator** [comment]
am I looking in the wrong place? screenshot for a sanity check: 

image

I tried `.fmtp`, `fmtrackplays`, `.fmtrackplays`, and a few other queries both in the [docs repo itself](https://github.com/fmbot-discord/docs) and the [hosted docs](https://fmbot.xyz/setup/) but I couldn't find any results...

is it because these commands are deprecated synonyms of `.tp`, `.trackplays`, etc.? I saw them used with the `fm` prefix recently in the .fmbot Discord server and I ended up here because I didn't find them in the docs

**Comment by curiositIy** [comment]
They are displayed with just the period prefix on the docs, not `.fm`

<https://fmbot.xyz/commands/tracks/#trackplays-tp>
<https://github.com/fmbot-discord/docs/search?q=trackplays>

**Pull request merged**
